### ISSUE TITLE
Programmatically set state the reactions

### ISSUE THREAD

**Issue by kirkcharlesniv** [GeekAbdelouahed/flutter-reaction-button#1]
How to set the reactions programmatically?

**Comment by jeff-forest** [comment]
example, when load/show the reaction button, we might want to show 'Wow' because previously the same user already selected 'Wow'. If not able to set the value of button then not able to show previously selected value.

**Comment by mostafaAbdelazim** [comment]
have you found a way to achieve this ?
@kirkcharlesniv  @jeff-forest

**Comment by mostafaAbdelazim** [comment]
Just posed a pull request for this, simply set isChecked to true and the selected reaction will be displayed instead of the initial one

**Comment by petchgabriel** [comment]
@GeekAbdelouahed I am facing the same problem here. Could you accept the pull request of @mostafaAbdelazim .

**Comment by GeekAbdelouahed** [comment]
@mostafaAbdelazim thanks bro
@petchgabriel done check it now

**Comment by petchgabriel** [comment]
> @mostafaAbdelazim thanks bro
> @petchgabriel done check it now

Thank you so much both of you. 😊
