### ISSUE TITLE
InitialReaction not updating as Expected/

### ISSUE THREAD

**Issue by ThalapathySiva** [GeekAbdelouahed/flutter-reaction-button#10]
Hey guys, first of all thanks for this plugin and i am facing the issue while implementing it in one of my project, could you guys help me out of this. Thanks in advance.  

Version : flutter_reaction_button: ^1.0.2

Here is my code:

                        FlutterReactionButtonCheck(
                             onReactionChanged: (reaction, isChecked) {
                             this.widget.post.isLike = !this.widget.post.isLike;
                            setState(() {});
                             print('reaction selected id: ${reaction.id}');
                               print('isChecked $isChecked');
                              },
                           reactions: Reactions.reactions,
                            initialReaction: this.widget.post.isLike
                              ? Reactions.reactions[0]
                            : Reactions.defaultInitialReaction,
                           selectedReaction: Reactions.reactions[0],
                            boxRadius: 26,
                            ),
                           ),

if you see the above code i am changing the initial reaction dynamically according to my needs whenever its change its not updating its always renders the first what we give to it. I saw the code of the implementation there its setted in initstate does that is prob or any other?  @GeekAbdelouahed  @mostafaAbdelazim

**Comment by mostafaAbdelazim** [comment]
Try setting isChecked constructor param to true and the initial reaction will be displayed by default 
@ThalapathySiva

**Comment by SchnMar** [comment]
Hey, also thank you for this plugin. I'm facing the same issue. I'm saving the reaction to a database and on reload I want the relevant reaction to be displayed as selected reaction. Unfortunately, the isChecked constructor is not available or I can't see it. 

@mostafaAbdelazim Can you please provide an example? Couldn't find it in the package examples...

Thank you

**Comment by mostafaAbdelazim** [comment]
@SchnMar 
It has been recently added in this PR
https://github.com/GeekAbdelouahed/flutter-reaction-button/pull/8
Maybe it's not updated on pub yet

**Comment by ThalapathySiva** [comment]
@mostafaAbdelazim  I have checked that can you try my code and see the result what i am facing? The things is if we change any of the reactions from the box its changing correctly if i not pressing longpress just pressed clicked its not changing to unlike thats the issue i am facing thanks for your reply.

**Comment by GeekAbdelouahed** [comment]
Hi @ThalapathySiva  thanks for your support.
I made few changes in the new version try it please

**Comment by ThalapathySiva** [comment]
@GeekAbdelouahed  thanks for your support the problem was on my side you can close this .
