### ISSUE TITLE
Is it possible to display the text above the icon?

### ISSUE THREAD

**Issue by bartonhammond** [GeekAbdelouahed/flutter-reaction-button#11]
![Screen Shot 2020-10-26 at 6 02 59 PM](https://user-images.githubusercontent.com/1282364/97237638-89011100-17b5-11eb-86c2-0f7f8be6dbbc.png)

**Comment by GeekAbdelouahed** [comment]
@bartonhammond  thanks for your suggestion, I've added it in the last version
```javascript
flutter_reaction_button: ^1.0.6
```
![flutter_01](https://user-images.githubusercontent.com/22131872/97776256-e525b580-1b66-11eb-8a79-0823ec24c96c.png)

**Comment by bartonhammond** [comment]
Nice - thanks.
