### ISSUE TITLE
Remove reaction not working

### ISSUE THREAD

**Issue by Naveenkumar3506** [GeekAbdelouahed/flutter-reaction-button#14]
Hi, When i set the FlutterReactionButtonCheck intiialReaction as "In Love", When i click again it should remove the reaction instead it adds "Happy' reaction. Can you please help me on this. Thanks in advance

**Comment by GeekAbdelouahed** [comment]
@Naveenkumar3506  Thanks for your using this package.
the issue fixed please try the last version
```javascript
flutter_reaction_button: ^1.0.6+1
```
