### ISSUE TITLE
FlutterReactionButtonCheck | buildWidgetPreview & buildWidget methods not provided

### ISSUE THREAD

**Issue by abelardolg** [GeekAbdelouahed/flutter-reaction-button#17]
Hi there,

At example of the FlutterReactionButtonCheck component, these methods don't exist. Also, they aren't mentioned in the documentation.

I guess the "buildWidget" method should return a Icon or an Image but I'm not sure.

Awesome component!!!!💓💓💓💓💓💓💓

**Comment by GeekAbdelouahed** [comment]
@abelardolg  Hi
you can find the content of it in the example code, but it just for demonstration purpose, in your code you should provide your own widget.
