### ISSUE TITLE
[QUESTION] How to close popover menu programmatically?

### ISSUE THREAD

**Issue by Mustahsan1** [GeekAbdelouahed/flutter-reaction-button#18]
Hi,

I want to close the popover reaction menu manually without user clicking outside the box, is there any possible way to achieve this?

Thanks in Advance

**Comment by GeekAbdelouahed** [comment]
Hi, @Mustahsan1 
you can use navigator to close it:
```dart
Navigator.pop(context);
```

**Comment by Mustahsan1** [comment]
Thanks alot @GeekAbdelouahed
