### ISSUE TITLE
Removal of ID is a breaking change

### ISSUE THREAD

**Issue by SchnMar** [GeekAbdelouahed/flutter-reaction-button#19]
Hello,

first of all, thank you very much for this great package.
Unfortunately, the removal of the ID was a breaking change for me which causes a lot of problems in my app. Can you please add an optional ID field again? 

Thank you!

**Comment by rajeshkulandaivel** [comment]
Yes. This is a breaking change and we need to have the Optional ID field. Please bring it back.
Thanks for the nice package.

> Hello,
> 
> first of all, thank you very much for this great package.
> Unfortunately, the removal of the ID was a breaking change for me which causes a lot of problems in my app. Can you please add an optional ID field again?
> 
> Thank you!

Yes it is breaking. please have it as optional.

**Comment by GeekAbdelouahed** [comment]
Hi, @SchnMar  , @rajeshkulandaivel 
i updated the package and add id reaction with deprecated annotation you can try the latest version.
```dart
flutter_reaction_button: ^1.0.7+3
```
ragards.
