### ISSUE TITLE
Top Position isn't on top of ReactionButton

### ISSUE THREAD

**Issue by SchnMar** [GeekAbdelouahed/flutter-reaction-button#20]
Hello,

I've got another issue. The reaction bar is not displayed on top of the reaction button, but there is little spacing between.
![image](https://user-images.githubusercontent.com/12902321/106109524-8c53c200-6141-11eb-8b10-fd2f65cedfa0.png)

Can you add more custom positioning attributes? This would help me and maybe https://github.com/GeekAbdelouahed/flutter-reaction-button/issues/13.

Thank you!

**Comment by hadihassan09** [comment]
Same issue!

**Comment by damian-kaczmarek** [comment]
Issue arise because of this line in ReactionBox
`  double _getTopPosition() =>
      widget.buttonOffset.dy - widget.buttonSize.height * 3.3;`
Maybe something like boxOffset should be added to FlutterReactionButton and used here so everyone can set it as they like.

**Comment by GeekAbdelouahed** [comment]
Check the last version @SchnMar 
```dart
flutter_reaction_button: ^2.0.0
```

**Comment by jigarfumakiya** [comment]
Any update here?
Is there anyway I can set offset @GeekAbdelouahed ?
