### ISSUE TITLE
Swipe gesture for reaction?

### ISSUE THREAD

**Issue by Dakrain** [GeekAbdelouahed/flutter-reaction-button#26]
Could implement the swipe gesture to choose reaction? Like hold to swipe and choose between reaction?

**Comment by GeekAbdelouahed** [comment]
Check the last version the feature is available right now.
```dart
flutter_reaction_button: ^2.0.0
```

**Comment by GeekAbdelouahed** [comment]
@Dakrain  please check the last version the feature is available right now.
```dart
flutter_reaction_button: ^2.0.0
```
