### ISSUE TITLE
Flutter 3.0.0 is detecting issue with the library

### ISSUE THREAD

**Issue by RoyalCoder88** [GeekAbdelouahed/flutter-reaction-button#36]
`../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_reaction_button-2.0.0+2/lib/src/ui/w
idget_size_render_object.dart:19:24: Warning: Operand of null-aware operation '?.' has type
'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart'
 ('../../../Documents/flutter/packages/flutter/lib/src/widgets/binding.dart').
        WidgetsBinding.instance?.addPostFrameCallback((_) {`

**Comment by hatemragab** [comment]
+1

**Comment by michaellifTelus** [comment]
+1
