### ISSUE TITLE
[Question] Can this be an alternative to popup menu?

### ISSUE THREAD

**Issue by jasonlaw** [GeekAbdelouahed/flutter-reaction-button#4]
Hi @GeekAbdelouahed ,

This is a very cool package.
I am thinking to use this as popup menu, hence, is there a way not to change the button to the selected reaction? 
Besides, it would be nice to have a enabled/disabled to the reaction item.

Thanks in advance.

**Comment by GeekAbdelouahed** [comment]
@jasonlaw  thanks for your interest, we've implemented your suggestions 😃
