### ISSUE TITLE
[Request] Popup position align with the button

### ISSUE THREAD

**Issue by jasonlaw** [GeekAbdelouahed/flutter-reaction-button#5]
Hi @GeekAbdelouahed ,

The popup is always at the center, it is pretty weird to see if we have short reaction items. Can we have an option to align it next the the button?

Thanks in advance.

**Comment by a7mdragab** [comment]
+1

**Comment by GeekAbdelouahed** [comment]
@jasonlaw hi,  check the last version 1.0.4
you can pass alignment value now:
`boxAlignment: Alignment.left`

**Comment by jasonlaw** [comment]
Thanks, really appreciate it.
