### ISSUE TITLE
[Question] How to update selected reaction programmatically

### ISSUE THREAD

**Issue by petchgabriel** [GeekAbdelouahed/flutter-reaction-button#9]
Assume I have 2 pages (Page A and B)

Page A have list of posts that contain a single FlutterReactionButtonCheck.
Page B have a single FlutterReactionButtonCheck

My scenario is when I go to Page B and update reaction from index 1 to 2. When I come back to Page A. I wanted update a FlutterReactionButtonCheck reaction.

What I have done is send callback function from Page A to Page B. Whenever the reaction changed i will call a callbackfunction to setState of a reaction in PageA. But it still not update.

This is a call back function in Page A
```
updateReaction(int newReaction) {
    print('update new reaction to: $newReaction');
    setState(() {
      this.userReaction = newReaction;
    });
}
```

This is a FlutterReactionButtonCheck setup in Page A.
```
FlutterReactionButtonCheck(
              onReactionChanged: (reaction, isChecked) async {
             ....
  },
  reactions: this.reactions,
  isChecked: this.userReaction == null ? false : true,
  initialReaction: GurubookReaction.defaultInitialReaction,
  selectedReaction: this.userReaction != null
  ? this.reactions[this.userReaction - 1]
  : this.reactions[0],
),
```

In page B whenever `onReactionChanged` called will trigger `updateReaction(reactions.id)`

Thanks in advance.

**Comment by GeekAbdelouahed** [comment]
@petchgabriel  check the last version please 1.0.3

**Comment by petchgabriel** [comment]
> @petchgabriel check the last version please 1.0.3

Thank you so much @GeekAbdelouahed . You save my days!!
